name: node-build-release

on:
  push:
    tags:
      - 'v*'

env:
  EXTENSION_NAME: splicing-url

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout/@v3
      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION2::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Create ChangeLog Text
        id: changelog_text
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/scripts/tag-changelog-config.js
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog_text.outputs.changes }}
          draft: false
          prerelease: false
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: |
          npm run build:v2 --if-present && npm run build:v3 --if-present
      - name: Upload Release Asset V2
        id: upload_release_asset_v2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./archive/${{ env.EXTENSION_NAME }}_manifest-v2_${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: ${{ env.EXTENSION_NAME }}_manifest-v2_${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset V3
        id: upload_release_asset_v3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./archive/${{ env.EXTENSION_NAME }}_manifest-v3_${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: ${{ env.EXTENSION_NAME }}_manifest-v3_${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
